// This file was AUTOMATICALLY GENERATED by dbg-import (smuggol) for github.com/robertkrimen/dbg

package main

import (
	Dbg "github.com/robertkrimen/godocdown/godocdown/dbg"
)

var dbg, dbgf = Dbg.New()
