// This file was AUTOMATICALLY GENERATED by kilt-import (smuggol) for github.com/robertkrimen/kilt

package main

import (
	Kilt "github.com/robertkrimen/godocdown/godocdown/kilt"
)

var kilt = Kilt.New()
