// This file was AUTOMATICALLY GENERATED by kilt-import (smuggol) from github.com/robertkrimen/kilt

package kilt

import (
	"os/exec"
)

// ExecCommand
func commandArguments(values ...string) []string {
	arguments := make([]string, 0, len(values))
	for _, value := range values {
		if value == "\x00" {
			continue
		}
		arguments = append(arguments, value)
	}
	return arguments
}

func (self Kilt) ExecCommand(program string, arguments ...string) *exec.Cmd {
	return ExecCommand(program, arguments...)
}

func ExecCommand(program string, arguments ...string) *exec.Cmd {
	return exec.Command(program, commandArguments(arguments...)...)
}
